/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.susana;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import oracle.jdbc.OracleTypes;

/**
 *
 * @author acer
 */
public class VentanaGestionPartes extends javax.swing.JFrame {

    /**
     * Creates new form GestionPartes
     */
    public VentanaGestionPartes() {
        initComponents();
         jTextField1LisPartePorTrabajador.requestFocus();
          this.setLocationRelativeTo(null);
    }

    Transportista tr;
    Parte pr;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jButton1partesAbiertos = new javax.swing.JButton();
        jButton2partesCerrados = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1ListPartesCerrados = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1ListPartesAbiertos1 = new javax.swing.JTextPane();
        jButton1ListarParaPoderEliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1LisPartePorTrabajador = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField1ListPartePorTrabyFech = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2EliminarParte = new javax.swing.JButton();
        Validad = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane1listadoUnParte = new javax.swing.JTextPane();
        jButton1ListarPartPorTrabYFecha = new javax.swing.JButton();
        jTextField1ListPartePorFecha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1partesAbiertos.setText("Partes abiertos");
        jButton1partesAbiertos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1partesAbiertosActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1partesAbiertos, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 22, -1, -1));

        jButton2partesCerrados.setText("Partes cerrados");
        jButton2partesCerrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2partesCerradosActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2partesCerrados, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jScrollPane1.setViewportView(jTextPane1ListPartesCerrados);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 828, 110));

        jScrollPane2.setViewportView(jTextPane1ListPartesAbiertos1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 56, 828, 123));

        jButton1ListarParaPoderEliminar.setText("Listar partes por fecha");
        jButton1ListarParaPoderEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ListarParaPoderEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1ListarParaPoderEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 403, 230, 40));

        jLabel1.setText("Trabajador");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 90, 20));

        jTextField1LisPartePorTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1LisPartePorTrabajadorActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1LisPartePorTrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 110, 20));

        jLabel3.setText("Fecha");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 90, -1));
        getContentPane().add(jTextField1ListPartePorTrabyFech, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, 110, -1));

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 500, -1, -1));

        jButton2EliminarParte.setText("Eliminar");
        jButton2EliminarParte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2EliminarParteActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2EliminarParte, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 500, -1, -1));

        Validad.setText("Validar");
        getContentPane().add(Validad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, -1, -1));

        jScrollPane3.setViewportView(jTextPane1listadoUnParte);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 830, 40));

        jButton1ListarPartPorTrabYFecha.setText("Listar partes por trabajador y fecha");
        jButton1ListarPartPorTrabYFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ListarPartPorTrabYFechaActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1ListarPartPorTrabYFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 230, 40));
        getContentPane().add(jTextField1ListPartePorFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 110, -1));

        jLabel4.setText("Fecha");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 90, -1));

        jButton2.setText("Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 500, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2partesCerradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2partesCerradosActionPerformed
        try {
            Class.forName("java.sql.DriverManager");
            Connection conexion = DriverManager.getConnection("jdbc:oracle:thin:@10.10.10.9:1521:db12102", "system", "oracle");

            Statement sentencia = conexion.createStatement();

            CallableStatement sql = conexion.prepareCall("{call LISTAPARTESCERRADOS(?)}");
            sql.registerOutParameter(1, OracleTypes.CURSOR);
            sql.execute();

            ResultSet resul = (ResultSet) sql.getObject(1);
            Document otroDocumento = jTextPane1ListPartesCerrados.getStyledDocument();
            while (resul.next()) {

                try {
                    otroDocumento.insertString(otroDocumento.getLength(),
                            "TRABAJADOR: " + resul.getString(11) + "   /   FECHA: " + resul.getString(3) + "   /   ESTADO: " + resul.getString(4) + "   /   KM PRINCIPIO: " + resul.getString(1) + "   /   KM FINAL: " + resul.getString(2) + "   /   GASTO GASOIL: " + resul.getString(5) + "   /   GASTO AUTOPISTA: " + resul.getString(6) + "   /   DIETAS: " + resul.getString(7) + "   /   GASTOS VARIOS: " + resul.getString(8) + "   /   INCIDENCIAS: " + resul.getString(9) + "   /   VALIDADO: " + resul.getString(10) + "   /   EXCESO: " + resul.getString(12) + "\n" + "\n", null);

                } catch (BadLocationException ble) {
                    ble.printStackTrace();
                }
            }
            resul.close();
            sentencia.close();
            conexion.close();
        } catch (ClassNotFoundException cn) {
            cn.printStackTrace();
        } catch (SQLException e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_jButton2partesCerradosActionPerformed

    private void jTextField1LisPartePorTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1LisPartePorTrabajadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1LisPartePorTrabajadorActionPerformed

    private void jButton1ListarParaPoderEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ListarParaPoderEliminarActionPerformed
        try {
            Class.forName("java.sql.DriverManager");
            Connection conexion = DriverManager.getConnection("jdbc:oracle:thin:@10.10.10.9:1521:db12102", "system", "oracle");

            Statement sentencia = conexion.createStatement();
            String trab = jTextField1LisPartePorTrabajador.getText();
            String fecha = jTextField1ListPartePorTrabyFech.getText();

            CallableStatement sql = conexion.prepareCall("{call LISTARUNPARTE(?, ?,  ?)}");
            sql.registerOutParameter(3, OracleTypes.CURSOR);
            sql.setString(1, trab);
            sql.setString(2, fecha);
            sql.execute();

            ResultSet resul = (ResultSet) sql.getObject(3);
            Document otroDocumento = jTextPane1listadoUnParte.getStyledDocument();
            while (resul.next()) {
                try {

                    pr.setUsuario(resul.getString(1));
                    pr.setFecha(resul.getDate(2).toString());
                    pr.setEstado(resul.getString(3));
                    pr.setKmPrincipio(Double.parseDouble(resul.getString(4)));
                    pr.setKmFinal(Double.parseDouble(resul.getString(5)));
                    pr.setGastoGasoil(Double.parseDouble(resul.getString(6)));
                    pr.setGastoAutopista(Double.parseDouble(resul.getString(7)));
                    pr.setGastoDietas(Double.parseDouble(resul.getString(8)));
                    pr.setGastosVarios(Double.parseDouble(resul.getString(9)));
                    pr.setIncidencias(resul.getString(10));
                    pr.setValidar(resul.getString(11));
                    pr.setExceso(Double.parseDouble(resul.getString(12)));
                    /*
                    TRABAJADOR_USUARIO, FECHA, ESTADO,  KM_PRINCIPIO, KM_FINAL, GASTO_GASOIL, GASTO_AUTOPISTA, 
GASTO_DIETAS, GASTOS_VARIOS, INCIDENCIAS, VALIDADO,  EXCESO
                     */
                    otroDocumento.insertString(otroDocumento.getLength(),
                            "TRABAJADOR_USUARIO: " + pr.getUsuario() + "\n" + "FECHA: " + pr.getFecha() + "\n" + "ESTADO: " + pr.getEstado() + "\n" + "KM PRINCIPIO: " + pr.getKmPrincipio()
                            + "\n" + "KM FINAL: " + pr.getKmFinal()
                            + "G. GASOIL: " + pr.getGastoGasoil() + "\n" + "g. AUTOPISTA: " + pr.getGastoAutopista()
                            + "DIETAS: " + pr.getGastoDietas() + "\n" + "G. VARIOS: " + pr.getGastosVarios() + "\n"
                            + "INCIDENCIAS: " + pr.getIncidencias() + "\n"
                            + "VALIDADO: " + pr.getValidar() + "\n"
                            + "EXCESO: " + pr.getExceso(), null);

                    if (jTextPane1listadoUnParte.getText().length() == 0) {
                        JOptionPane.showMessageDialog(this, "trabajador inexistente con los datos indicados");
                    }

                } catch (BadLocationException ble) {
                    ble.printStackTrace();

                }

            }

            resul.close();
            sentencia.close();
            conexion.close();

        } catch (ClassNotFoundException cn) {
            cn.printStackTrace();

        } catch (SQLException e) {
            e.printStackTrace();

        }
        //fuente: aprenderaprogramar.com/foros/index.php?topic=1235.0
        if (jTextPane1listadoUnParte.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "trabajador inexistente con los datos indicados");
        }
    }//GEN-LAST:event_jButton1ListarParaPoderEliminarActionPerformed

    private void jButton1partesAbiertosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1partesAbiertosActionPerformed
        try {
            Class.forName("java.sql.DriverManager");
            Connection conexion = DriverManager.getConnection("jdbc:oracle:thin:@10.10.10.9:1521:db12102", "system", "oracle");

            Statement sentencia = conexion.createStatement();

            CallableStatement sql = conexion.prepareCall("{call LISTAPARTESABIERTOS(?)}");
            sql.registerOutParameter(1, OracleTypes.CURSOR);
            sql.execute();

            ResultSet resul = (ResultSet) sql.getObject(1);
            Document otroDocumento = jTextPane1ListPartesAbiertos1.getStyledDocument();
            while (resul.next()) {

                try {
                    otroDocumento.insertString(otroDocumento.getLength(),
                            "TRABAJADOR: " + resul.getString(11) + "   /   FECHA: " + resul.getString(3) + "   /   ESTADO: " + resul.getString(4) + "   /   KM PRINCIPIO: " + resul.getString(1) + "   /   KM FINAL: " + resul.getString(2) + "   /   GASTO GASOIL: " + resul.getString(5) + "   /   GASTO AUTOPISTA: " + resul.getString(6) + "   /   DIETAS: " + resul.getString(7) + "   /   GASTOS VARIOS: " + resul.getString(8) + "   /   INCIDENCIAS: " + resul.getString(9) + "   /   VALIDADO: " + resul.getString(10) + "   /   EXCESO: " + resul.getString(12) + "\n" + "\n", null);

                } catch (BadLocationException ble) {
                    ble.printStackTrace();
                }
            }
            resul.close();
            sentencia.close();
            conexion.close();
        } catch (ClassNotFoundException cn) {
            cn.printStackTrace();
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton1partesAbiertosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2EliminarParteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2EliminarParteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2EliminarParteActionPerformed

    private void jButton1ListarPartPorTrabYFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ListarPartPorTrabYFechaActionPerformed
       try {
            Class.forName("java.sql.DriverManager");
            Connection conexion = DriverManager.getConnection("jdbc:oracle:thin:@10.10.10.9:1521:db12102", "system", "oracle");

            Statement sentencia = conexion.createStatement();
            String trab = jTextField1LisPartePorTrabajador.getText();
            String fecha = jTextField1ListPartePorTrabyFech.getText();

            CallableStatement sql = conexion.prepareCall("{call LISTARUNPARTE(?, ?,  ?)}");
            sql.registerOutParameter(3, OracleTypes.CURSOR);
            sql.setString(1, trab);
            sql.setString(2, fecha);
            sql.execute();

            ResultSet resul = (ResultSet) sql.getObject(3);
            Document otroDocumento = jTextPane1listadoUnParte.getStyledDocument();
            while (resul.next()) {
                try {

                    pr.setUsuario(resul.getString(1));
                    pr.setFecha(resul.getDate(2).toString());
                    pr.setEstado(resul.getString(3));
                    pr.setKmPrincipio(Double.parseDouble(resul.getString(4)));
                    pr.setKmFinal(Double.parseDouble(resul.getString(5)));
                    pr.setGastoGasoil(Double.parseDouble(resul.getString(6)));
                    pr.setGastoAutopista(Double.parseDouble(resul.getString(7)));
                    pr.setGastoDietas(Double.parseDouble(resul.getString(8)));
                    pr.setGastosVarios(Double.parseDouble(resul.getString(9)));
                    pr.setIncidencias(resul.getString(10));
                    pr.setValidar(resul.getString(11));
                    pr.setExceso(Double.parseDouble(resul.getString(12)));
                    /*
                    TRABAJADOR_USUARIO, FECHA, ESTADO,  KM_PRINCIPIO, KM_FINAL, GASTO_GASOIL, GASTO_AUTOPISTA, 
GASTO_DIETAS, GASTOS_VARIOS, INCIDENCIAS, VALIDADO,  EXCESO
                     */
                    otroDocumento.insertString(otroDocumento.getLength(),
                            "TRABAJADOR_USUARIO: " + pr.getUsuario() + "\n" + "FECHA: " + pr.getFecha() + "\n" + "ESTADO: " + pr.getEstado() + "\n" + "KM PRINCIPIO: " + pr.getKmPrincipio()
                            + "\n" + "KM FINAL: " + pr.getKmFinal()
                            + "G. GASOIL: " + pr.getGastoGasoil() + "\n" + "g. AUTOPISTA: " + pr.getGastoAutopista()
                            + "DIETAS: " + pr.getGastoDietas() + "\n" + "G. VARIOS: " + pr.getGastosVarios() + "\n"
                            + "INCIDENCIAS: " + pr.getIncidencias() + "\n"
                            + "VALIDADO: " + pr.getValidar() + "\n"
                            + "EXCESO: " + pr.getExceso(), null);

                  

                } catch (BadLocationException ble) {
                    ble.printStackTrace();

                }

            }

            resul.close();
            sentencia.close();
            conexion.close();

        } catch (ClassNotFoundException cn) {
            cn.printStackTrace();

        } catch (SQLException e) {
            e.printStackTrace();

        }
        //fuente: aprenderaprogramar.com/foros/index.php?topic=1235.0
        if (jTextPane1listadoUnParte.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Parte inexistente con los datos indicados");
        }
                                                                   


    }//GEN-LAST:event_jButton1ListarPartPorTrabYFechaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        VentanaAdministrador va = new VentanaAdministrador();
        va.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionPartes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionPartes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionPartes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionPartes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaGestionPartes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Validad;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1ListarParaPoderEliminar;
    private javax.swing.JButton jButton1ListarPartPorTrabYFecha;
    private javax.swing.JButton jButton1partesAbiertos;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton2EliminarParte;
    private javax.swing.JButton jButton2partesCerrados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1LisPartePorTrabajador;
    private javax.swing.JTextField jTextField1ListPartePorFecha;
    private javax.swing.JTextField jTextField1ListPartePorTrabyFech;
    private javax.swing.JTextPane jTextPane1ListPartesAbiertos1;
    private javax.swing.JTextPane jTextPane1ListPartesCerrados;
    private javax.swing.JTextPane jTextPane1listadoUnParte;
    // End of variables declaration//GEN-END:variables
}
