/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.susana.GUI;

import com.susana.Entidades.Parte;
import com.susana.Entidades.Transportista;
import com.susana.Entidades.Viaje;
import com.susana.LogicaNegocio.ViajesLN;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import oracle.jdbc.OracleTypes;

/**
 *
 * @author acer
 */
public class VentanaViajes extends javax.swing.JFrame {

    ViajesLN partes;
    Transportista tr;
    Viaje vj;
    private DefaultTableModel modeloDeTabla;

    /**
     * Creates new form Viajes
     */
    public VentanaViajes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1Viajes = new javax.swing.JTable();
        jButton1VerPartes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("VIAJES");
        setEnabled(false);

        jTable1Viajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "VIAJE", "HORA SALIDA", "HORA LLEGADA", "MATRICULA VEHICULO", "FECHA PARTE", "TOTAL HORAS VIAJE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Long.class, java.lang.Long.class, java.lang.String.class, java.lang.Object.class, java.lang.Long.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1Viajes);

        jButton1VerPartes.setText("Ver viajes");
        jButton1VerPartes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1VerPartesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jButton1VerPartes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton1VerPartes)
                .addContainerGap(313, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1VerPartesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1VerPartesActionPerformed
  /* modeloDeTabla = (DefaultTableModel) jTable1Viajes.getModel();

        try {
            Class.forName("java.sql.DriverManager");
            Connection conexion = DriverManager.getConnection("jdbc:oracle:thin:@10.10.10.9:1521:db12102", "system", "oracle");

            Statement sentencia = conexion.createStatement();

            CallableStatement sql = null;

            for (int i = 0; i < modeloDeTabla.getRowCount(); i++) {
                modeloDeTabla.removeRow(i);
                i -= 1;
            }
           
                sql = conexion.prepareCall("{call LISTARVIAJES(?)}");
           
            sql.registerOutParameter(1, OracleTypes.CURSOR);
            sql.execute();

            ResultSet resul = (ResultSet) sql.getObject(1);
            while (resul.next()) {

                try {
                    vj = new Viaje();
                    vj.setIdViaje(Integer.parseInt(resul.getString(1)));
                    vj.setHoraSalida (Integer.parseInt(resul.getString(2)));
                    vj.setHoraLlegada(Integer.parseInt(resul.getString(3)));
                    vj.setMatricula(resul.getString(4));
                    vj.setFecha(resul.getDate(5));
                    vj.setTotalHorasViaje(Integer.parseInt(resul.getString(6)));


                    modeloDeTabla.insertRow(modeloDeTabla.getRowCount(),
                            new Object[]{vj.getIdViaje(), vj.HoraSalida(), pr.getFecha(), pr.getEstado(),
                                pr.getKmPrincipio(), pr.getKmFinal(), pr.getGastoGasoil(), pr.getGastoAutopista(),
                                pr.getGastoDietas(), pr.getGastosVarios(), pr.getIncidencias(), pr.getValidar(), pr.getExceso()});

                    otroDocumento.insertString(otroDocumento.getLength(),
                            "NUM. PARTE: " + pr.getNumParte() + "   /   USUARIO: " + pr.getUsuario()
                            + "   /   FECHA: " + pr.getFecha() + "   /   ESTADO: " + pr.getEstado()
                            + "   /   KM PRINCIPIO: " + pr.getKmPrincipio() + "   /   KM FINAL: " + pr.getKmFinal()
                            + "   /   GASTO GASOIL: " + pr.getGastoGasoil() + "   /   GASTO AUTOPISTA: " + pr.getGastoAutopista()
                            + "   /   DIETAS: " + pr.getGastoDietas() + "   /   GASTOS VARIOS: " + pr.getGastosVarios()
                            + "   /   INCIDENCIAS: " + pr.getIncidencias() + "   /   VALIDADO: " + pr.getValidar()
                            + "   /   EXCESO: " + pr.getExceso() + "\n" + "\n", null);
                    if (modeloDeTabla.getRowCount() == 0) {
                        JOptionPane.showMessageDialog(this, "Parte inexistente con los datos indicados");
                    }

                } catch (BadLocationException ble) {
                    ble.printStackTrace();
                }
            }
            if (modeloDeTabla.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Parte inexistente con los datos indicados");
            }
            resul.close();
            sentencia.close();
            conexion.close();

        } catch (ClassNotFoundException cn) {
            cn.printStackTrace();

        } catch (SQLException e) {
            e.printStackTrace();
        } catch (BadLocationException ex) {
            Logger.getLogger(VentanaGestionPartes.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    }//GEN-LAST:event_jButton1VerPartesActionPerformed
*/
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaViajes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1VerPartes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1Viajes;
    // End of variables declaration//GEN-END:variables
}
