/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.susana.GUI;

import com.susana.Entidades.Parte;
import com.susana.Entidades.Transportista;
import com.susana.Entidades.Viaje;
import com.susana.LogicaNegocio.ViajesLN;
import com.susana.DAO.PartesDAO;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import oracle.jdbc.OracleTypes;

/**
 *
 * @author acer
 */
public class VentanaViajes extends javax.swing.JFrame {

    ViajesLN partes;
    Transportista tr;
    Viaje vj;
    private DefaultTableModel modeloDeTabla;

    /**
     * Creates new form Viajes
     */
    public VentanaViajes() {
        initComponents();
        vj = new Viaje();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1Salir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1Viajes = new javax.swing.JTable();
        jButton1VerViajes = new javax.swing.JButton();
        jButton3Volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("VIAJES");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1Salir.setText("Salir");
        jButton1Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1SalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, -1, -1));

        jTable1Viajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID VIAJE", "HORA SALIDA", "HORA LLEGADA", "MATRICULA VEHICULO", "TOTAL HORAS VIAJE", "NUM PARTE", "USUARIO", "FECHA "
            }
        ));
        jTable1Viajes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1ViajesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1Viajes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 789, 290));

        jButton1VerViajes.setText("Ver viajes");
        jButton1VerViajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1VerViajesActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1VerViajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 100, -1));

        jButton3Volver.setText("Volver");
        jButton3Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3VolverActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 330, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

//TODO: VIAJES

    private void jButton1VerViajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1VerViajesActionPerformed
        try {
            modeloDeTabla = (DefaultTableModel) jTable1Viajes.getModel();
            ViajesLN vln = new ViajesLN();
            List<Viaje> viajes = vln.listarDatos(vj);
            for (int i = 0; i < viajes.size(); i++) {
                modeloDeTabla.insertRow(modeloDeTabla.getRowCount(),
                        new Object[]{vj.getIdViaje(), vj.getHoraSalida(), vj.getHoraLlegada(),
                            vj.getMatricula(), vj.getFecha(), vj.getUsuario(), vj.getTotalHorasViaje()});
            }
            
            if (modeloDeTabla.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Viaje inexistente con los datos indicados");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VentanaViajes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1VerViajesActionPerformed

    //OPCIÓN PARA SALIR DEL PROGRAMA

    private void jButton1SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1SalirActionPerformed

    //VOLVER A GESTIÓN PARTES

    private void jButton3VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3VolverActionPerformed
        VentanaGestionPartes va = new VentanaGestionPartes();
        va.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3VolverActionPerformed

    private void jTable1ViajesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1ViajesMouseClicked

    }//GEN-LAST:event_jTable1ViajesMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaViajes().setVisible(true);

            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Salir;
    private javax.swing.JButton jButton1VerViajes;
    private javax.swing.JButton jButton3Volver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1Viajes;
    // End of variables declaration//GEN-END:variables

    void setUsuario(String usuario) {
        this.vj.setUsuario(usuario);
    }

    void setNumParte(String numParte) {
        this.vj.setNumParte(Integer.valueOf(numParte));
    }
}
