/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.susana.GUI;

import com.susana.Entidades.Viaje;
import com.susana.LogicaNegocio.ViajesLN;
import java.sql.Date;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZoneId;
import static java.time.temporal.ChronoUnit.MINUTES;

/**
 *
 * @author acer
 */
public class VentanaInsertarViajes extends javax.swing.JFrame {

    private Integer numParte;
    private Integer idViaje;
    private LocalDate f;

    /**
     * Creates new form VentanaInsertarViajes
     */
    public VentanaInsertarViajes() {
        initComponents();
        this.dispose();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jDateChooserFechaParte = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField3MatriculaVehiculo = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jBInsertarViaje = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jSpinner1HoraSalida = new javax.swing.JSpinner();
        jSpinner2MinutoSalida = new javax.swing.JSpinner();
        jSpinner1HoraLlegada = new javax.swing.JSpinner();
        jSpinner2MinutoLlegada = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setText("FECHA");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 150, 10));

        jDateChooserFechaParte.setEnabled(false);
        getContentPane().add(jDateChooserFechaParte, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 230, 30));

        jLabel13.setText("HORA SALIDA");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 150, -1));

        jLabel14.setText("HORA LLEGADA");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 150, -1));
        getContentPane().add(jTextField3MatriculaVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 200, 30));

        jLabel15.setText("MATRICULA VEHICULO");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 150, -1));

        jLabel2.setText("USUARIO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 100, -1));

        jTextFieldUsuario.setEnabled(false);
        jTextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 310, 30));

        jButton3.setText("Volver");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, -1, -1));

        jBInsertarViaje.setText("Insertar viaje");
        jBInsertarViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInsertarViajeActionPerformed(evt);
            }
        });
        getContentPane().add(jBInsertarViaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 140, 40));

        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jBSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 60, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSpinner1HoraSalida.setModel(new javax.swing.SpinnerNumberModel(0, 0, 24, 1));
        jPanel1.add(jSpinner1HoraSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 40, -1));

        jSpinner2MinutoSalida.setModel(new javax.swing.SpinnerNumberModel(0, 0, 60, 1));
        jPanel1.add(jSpinner2MinutoSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 40, -1));

        jSpinner1HoraLlegada.setModel(new javax.swing.SpinnerNumberModel(0, 0, 24, 1));
        jPanel1.add(jSpinner1HoraLlegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 40, -1));

        jSpinner2MinutoLlegada.setModel(new javax.swing.SpinnerNumberModel(0, 0, 60, 1));
        jPanel1.add(jSpinner2MinutoLlegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 40, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        VentanaCrearParteLogistica va = new VentanaCrearParteLogistica();
        va.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jBInsertarViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInsertarViajeActionPerformed
        ViajesLN vln = new ViajesLN();
        Viaje v = new Viaje();
        if (idViaje != null) {
            v.setIdViaje(idViaje);
        }
        /*
        pagina stackoverflow.com Convert java.util.Date to java.time.LocalDate.
         solución a problemas java util date tiene problemas de entendimiento de zona horaria.  

         */
        v.setFecha(jDateChooserFechaParte.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
        v.setHoraLlegada(LocalTime.now()
                .withHour((int) jSpinner1HoraLlegada.getValue())
                .withMinute((int) jSpinner2MinutoLlegada.getValue())
                .withSecond(0)
                .withNano(0));
        v.setHoraSalida(LocalTime.now()
                .withHour((int) jSpinner1HoraSalida.getValue())
                .withMinute((int) jSpinner2MinutoSalida.getValue())
                .withSecond(0)
                .withNano(0));
        v.setMatricula(jTextField3MatriculaVehiculo.getText());
        v.setTotalHorasViaje( v.getHoraLlegada().until(v.getHoraSalida(),MINUTES));

        if (numParte == null) {
            numParte = vln.insertarDatos(v);
        } else {
            vln.actualizarDatos(v);
        }
    }//GEN-LAST:event_jBInsertarViajeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInsertarViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInsertarViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInsertarViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInsertarViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInsertarViajes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBInsertarViaje;
    private javax.swing.JButton jBSalir;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooserFechaParte;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinner1HoraLlegada;
    private javax.swing.JSpinner jSpinner1HoraSalida;
    private javax.swing.JSpinner jSpinner2MinutoLlegada;
    private javax.swing.JSpinner jSpinner2MinutoSalida;
    private javax.swing.JTextField jTextField3MatriculaVehiculo;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables

    void setNumParte(Integer numParte) {
        this.numParte = numParte;
    }

    void setFechaViaje(Date fecha) {

        jDateChooserFechaParte.setDate(fecha);
    }

    void setUsuario(String usuario) {
        jTextFieldUsuario.setText(usuario);
    }
//inutilizar casilla matricula cuando ya hay un vehiculo utilizado, para que sea el mismo

    void setMatricula(String matricula) {
        jTextField3MatriculaVehiculo.setText(matricula);
        jTextField3MatriculaVehiculo.setEnabled(false);
    }
}
