--LISTADO DE TODOS LOS CENTROS

create or replace procedure LISTACENTROS (LISTAC OUT SYS_REFCURSOR)
AS
VACIO EXCEPTION;
MAS_ERRORES EXCEPTION;
BEGIN
OPEN LISTAC FOR
SELECT * FROM CENTRO;
EXCEPTION
WHEN NO_DATA_FOUND THEN RAISE VACIO;
WHEN OTHERS THEN RAISE MAS_ERRORES;
END LISTACENTROS;

--LISTADO DE UN CENTRO

create or replace PROCEDURE LISTARUNCENTRO ( NOMBRE_CENTRO IN CENTRO.NOMBRE%TYPE, TODO OUT CENTRO%ROWTYPE)
IS
VACIO EXCEPTION;
MAS_ERRORES EXCEPTION;
BEGIN
SELECT * INTO TODO FROM CENTRO WHERE NOMBRE = NOMBRE_CENTRO;
EXCEPTION
WHEN NO_DATA_FOUND THEN RAISE VACIO;
WHEN OTHERS THEN RAISE MAS_ERRORES;
END LISTARUNCENTRO;

--LISTAR UN TRABAJADOR

create or replace PROCEDURE LISTARUNTRABAJADOR ( dni_trabajador IN TRABAJADOR.DNI%TYPE, TODO OUT TRABAJADOR%ROWTYPE)
IS
VACIO EXCEPTION;
MAS_ERRORES EXCEPTION;
BEGIN
SELECT * INTO TODO FROM TRABAJADOR WHERE DNI = dni_trabajador;
EXCEPTION
WHEN NO_DATA_FOUND THEN RAISE VACIO;
WHEN OTHERS THEN RAISE MAS_ERRORES;
END LISTARUNTRABAJADOR;

--LISTAR TRABAJADORES
create or replace procedure LISTATRABAJADORES (LISTA OUT SYS_REFCURSOR)
AS
VACIO EXCEPTION;
MAS_ERRORES EXCEPTION;
BEGIN
OPEN LISTA FOR
SELECT * FROM TRABAJADOR;
EXCEPTION
WHEN NO_DATA_FOUND THEN RAISE VACIO;
WHEN OTHERS THEN RAISE MAS_ERRORES;
END LISTATRABAJADORES;

--TRABAJADORES CON PARTES ABIERTOS

create or replace PROCEDURE TRAB_PARTES_ABIERTOS (TRAB_ABIERTOS OUT SYS_REFCURSOR)
IS
VACIO EXCEPTION;
MAS_ERRORES EXCEPTION;
BEGIN
OPEN TRAB_ABIERTOS FOR
SELECT T.USUARIO, T.DNI, T.NOMBRE, T.APELLIDO_1, T.APELLIDO_2, T.CALLE, T.PISO, T.MANO, T.CATEGORIA, T.CENTRO_CENTRO_ID , P.ESTADO FROM TRABAJADOR T, PARTE P
WHERE TRABAJADOR_USUARIO = USUARIO AND P.ESTADO = 'ABIERTO';
EXCEPTION
WHEN NO_DATA_FOUND THEN RAISE VACIO;
WHEN OTHERS THEN RAISE MAS_ERRORES;
END TRAB_PARTES_ABIERTOS;

--TRABAJADORES CON PARTES CERRADOS

create or replace PROCEDURE TRAB_PARTES_CERRADOS (TRAB_CERRADOS OUT SYS_REFCURSOR)
IS
VACIO EXCEPTION;
MAS_ERRORES EXCEPTION;
BEGIN
OPEN TRAB_CERRADOS FOR
SELECT T.USUARIO, T.DNI, T.NOMBRE, T.APELLIDO_1, T.APELLIDO_2, T.CALLE, T.PISO, T.MANO, T.CATEGORIA, T.CENTRO_CENTRO_ID, P.ESTADO
FROM TRABAJADOR T, PARTE P
WHERE P.TRABAJADOR_USUARIO = T.USUARIO AND P.ESTADO = 'CERRADO';
EXCEPTION
WHEN NO_DATA_FOUND THEN RAISE VACIO;
WHEN OTHERS THEN RAISE MAS_ERRORES;
END TRAB_PARTES_CERRADOS;