create or replace PROCEDURE LISTARUNCENTRO (  NOMBRE_CENTRO IN CENTRO.NOMBRE%TYPE, todo OUT sys_refcursor)
IS
VACIO EXCEPTION;
MAS_ERRORES EXCEPTION;  
BEGIN
open todo for
SELECT NOMBRE, CALLE, NUMERO, CODIGO_POSTAL, TELEFONO, CIUDAD, PROVINCIA, CENTRO_ID FROM CENTRO WHERE NOMBRE = NOMBRE_CENTRO;
EXCEPTION
WHEN NO_DATA_FOUND THEN RAISE VACIO;
END LISTARUNCENTRO;

create or replace procedure LISTACENTROS (LISTAC OUT SYS_REFCURSOR)
AS
VACIO EXCEPTION;
MAS_ERRORES EXCEPTION;
BEGIN
OPEN LISTAC FOR
SELECT * FROM CENTRO;
EXCEPTION
WHEN NO_DATA_FOUND THEN RAISE VACIO;
WHEN OTHERS THEN RAISE MAS_ERRORES;
END LISTACENTROS;

create or replace procedure LISTATRABAJADORES (LISTA OUT SYS_REFCURSOR)
AS
VACIO EXCEPTION;
MAS_ERRORES EXCEPTION;
BEGIN
OPEN LISTA FOR
SELECT * FROM TRABAJADOR;
EXCEPTION
WHEN NO_DATA_FOUND THEN RAISE VACIO;
WHEN OTHERS THEN RAISE MAS_ERRORES;
END LISTATRABAJADORES;

create or replace PROCEDURE LISTARUNTRABAJADOR ( dni_trabajador IN TRABAJADOR.DNI%TYPE, TODO OUT sys_refcursor)
IS
VACIO EXCEPTION;
MAS_ERRORES EXCEPTION;  
BEGIN
open todo for
SELECT DNI, NOMBRE, APELLIDO_1, APELLIDO_2, CALLE, PORTAL, PISO, MANO, CATEGORIA, CENTRO_CENTRO_ID, TELEFONO_EMPRESA, TELEFONO_PERSONAL, SALARIO, FECHA_NACIMIENTO FROM TRABAJADOR WHERE DNI = dni_trabajador;
EXCEPTION
WHEN NO_DATA_FOUND THEN RAISE VACIO;
END LISTARUNTRABAJADOR;

