create or replace PROCEDURE PARTESPORFECHA (  FECHA_PARTE IN PARTE.FECHA%TYPE, todo OUT sys_refcursor)
IS
VACIO EXCEPTION;
MAS_ERRORES EXCEPTION;  
BEGIN
open todo for
SELECT KM_PRINCIPIO, KM_FINAL, FECHA, ESTADO, GASTO_GASOIL, GASTO_AUTOPISTA, GASTO_DIETAS, GASTOS_VARIOS, INCIDENCIAS
FROM PARTE WHERE FECHA_PARTE = FECHA;
EXCEPTION
WHEN NO_DATA_FOUND THEN RAISE VACIO;
END PARTESPORFECHA;

COMMIT;

INSERT INTO PARTE VALUES (125, 150, SYSDATE, 'ABIERTO', 20, 10, 50, 10, 'Pinchazo rueda delantera', 0, 'PZQT');
ALTER TABLE PARTE
RENAME COLUMN INDICENCIAS TO INCIDENCIAS;
select*from centro;
select* from parte;
select * from trabajador;
describe parte;
describe centro;