create or replace PROCEDURE LISTARUNTRABAJADOR ( dni_trabajador IN TRABAJADOR.DNI%TYPE, TODO OUT sys_refcursor)
IS
VACIO EXCEPTION;
MAS_ERRORES EXCEPTION;  
BEGIN
open todo for
SELECT DNI, NOMBRE, APELLIDO_1, APELLIDO_2, CALLE, PORTAL, PISO, MANO, CATEGORIA, CENTRO_CENTRO_ID, TELEFONO_EMPRESA, TELEFONO_PERSONAL, SALARIO, FECHA_NACIMIENTO FROM TRABAJADOR WHERE DNI = dni_trabajador;
EXCEPTION
WHEN NO_DATA_FOUND THEN RAISE VACIO;
END LISTARUNTRABAJADOR;

select * from trabajador;
COMMIT;